export const questions = [
  {
    id: 1,
    time: 15,
    question: "Why did Mike initially ignore Myra's behavior?",
    options: [
      "He thought it was accidental",
      "He liked the attention",
      "He wanted a promotion",
      "He didn't know Myra",
    ],
    answer: 0,
  },
  {
    id: 2,
    time: 40,
    question: "How did Myra's behavior change over time?",
    options: [
      "She stopped talking to Mike",
      "She became more professional",
      "She made direct sexual advances",
      "She transferred to another team",
    ],
    answer: 2,
  },
  {
    id: 3,
    time: 68,
    question: "What did Myra ask Mike to do during the company outbound event?",
    options: [
      "Join her for dinner",
      "Massage her back in her room",
      "Prepare a presentation",
      "Drive her back home",
    ],
    answer: 1,
  },
  {
    id: 4,
    time: 94,
    question: "Why did Mike hesitate to report the harassment?",
    options: [
      "He was planning to resign",
      "He feared workplace consequences",
      "He didn't know Myra's name",
      "He wanted to ignore the issue",
    ],
    answer: 1,
  },
  {
    id: 5,
    time: 120,
    question: "Why was Mike unsure about approaching the POSH Internal Committee?",
    options: [
      "He thought the committee didn't exist",
      "He believed the POSH Act is women-centric",
      "He didn't know where the office was",
      "He was on leave",
    ],
    answer: 1,
  },
  {
    id: 6,
    time: 148,
    question: "Why are many organizations adopting a gender-neutral POSH policy?",
    options: [
      "To reduce paperwork",
      "To protect individuals of all genders from workplace sexual harassment",
      "To increase employee salaries",
      "To simplify hiring",
    ],
    answer: 1,
  },
  {
    id: 7,
    time: 170,
    question: "According to the speaker, what should Mike do?",
    options: [
      "Ignore the situation",
      "Resign immediately",
      "Approach the organization's POSH Internal Committee and explain his situation",
      "Confront Myra privately",
    ],
    answer: 2,
  },
];